---
functional:
 - Пользователь может зарегистрироваться на сайте с помощью своей почты или с помощью своего аккаунта на GitHub.
 - Пользователь может начать "игру" без регистрации.
 - Пользователь может создать "игру" с другим пользователем или ботом.
 - При создании игры пользователю предоставляется настройка выбора сложности, типа, времени, задания.
 - Пользователь может просмотреть свои и чужие (других зарегистрированных пользователей) завершенные сеансы "игр".
 - На главной странице сайта должна отображаться таблица лидеров с фильтром по времени (за день/месяц/все время)
 - 
non-functional:
- требование 3
- требование 4
implicit:
- требование 5
- требование 6
