---
functional:
 - Пользователь может зарегистрироваться на сайте с помощью своей почты или с помощью своего аккаунта на GitHub.
 - Пользователь может начать "игру" без регистрации.
 - Пользователь может создать "игру" с другим пользователем или ботом.
 - При создании игры пользователю предоставляется возможность настройки по фильтрам
   1. выбор сложности задания
   2. выбор соперника
   3. ограничение по времени
   4. выбор задания
 - Пользователь может просмотреть свои и чужие (других зарегистрированных пользователей) завершенные сеансы "игр".
 - На главной странице сайта должна отображаться таблица лидеров по очкам с фильтром по времени (за неделю/месяц/все время)
 - Сайт должен быть полностью переведен на два языка
   русский и английский.
 - На главной странице сайта должно отображаться лобби с возможностью выбора соперника по новой игре.
 - Завершенные игры должны быть доступны в записи.
 - Пользователь должен получать очки за победы в играх, на основе которых состовляется рейтинг лидеров
 - Пользователь может следить за ходом игры других пользователей.
 - В лобби и в любой игре есть чат, куда могут писать комментарии пользователи
non-functional:
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен иметь мобильную версию.
- Сайт должен быть способен обрабатывать большое количество трафика (1000 одновременных пользователей)
- Сайт имеет расширерие для браузера google chrome 
implicit:
- Сайт должен быть безопасным и защищать данные пользователя
# НЕзавершенность : Отсутствуют нефункциональные составляющие требования.
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
# НЕоднозначность : Использование терминов или фраз, допускающих субъективное толкование.
- Пользователь не должен иметь возможность редактировать код соперника и в завершенных партиях..
- Пользователь должен иметь возможность сменить пароль.
# НЕоднозначность : Использование терминов или фраз, допускающих субъективное толкование.
