---
functional:
- The user can sign up on the website.
- The user can sign in using GitHub account.
- The user can start the game without sign in.
- User can create a game with another user or bot.
- Available game options
  1. task difficulty
  2. choice of opponent
  3. time delay
  4. task selection
- The user can view completed sessions of games.
- On the main page there should be a leaderboard by points with a filter by time (per week / month / all time)
- The website must be fully translated into two languages:Russian and English.
- On the main page there should be a lobby with the ability to select game opponent.
- A record of completed games must be available for viewing.
- The user must receive points for winning games.
- The user can follow the progress of the game of other players.
- There is a chat in the lobby and in the game where users can write comments.
- Выбор языка программирования

non-functional:
- The site must be tested for compatibility with the latest browser versions
- The website must be mobile friendly.
- The site must be able to handle a large amount of traffic (1000 concurrent users)

implicit:
- The website must have a chrome browser extension
# Ambiguity : The use of terms or phrases that are subjective.
- The website must be secure and protect user data
# Incomplete : There are no non-functional parts of the requirement.
- The website must be designed with usability in mind and optimized for speed
# Ambiguity : The use of terms or phrases that are subjective.
- The user should not be able to edit the opponent's code in completed games.
# Ambiguity : The use of terms or phrases that are subjective.
- User must be able to change password.
# Ambiguity : The use of terms or phrases that are subjective

